# Data Analysis

## Step 1: Import the Required Libraries

In [1]:
import pandas as pd

## Step 2: Load the Data

In [3]:
customers = pd.read_parquet("../../data/cleaned/customers.parquet")
transactions = pd.read_parquet("../../data/cleaned/transactions.parquet")

## Step 2: Data Analysis

### 5.1 GroupBy

#### 1. Number of Transactions by Product Category
**Question:**  
How many transactions are there in each `product_category`?

In [4]:
transactions.groupby("product_category").size()

product_category
Audio Equipment             1884
Bedding                      639
Computer Accessories         628
Cookware                     639
Desktop Computers            664
Furniture                   3905
Gaming Consoles             1892
Home Decor                  3704
Kitchen Appliances          3693
Laptops                     1889
Small Kitchen Appliances    1331
Smart Home Devices          4314
Smartphones                 4407
TVs                         1346
Tablets                      674
dtype: int64

###### 2. Total Quantity Sold by Product Category

**Question:**  
What is the total `quantity` sold for each `product_category`?

In [5]:
transactions.groupby("product_category")["quantity"].sum()

product_category
Audio Equipment             2557.0
Bedding                      922.0
Computer Accessories         887.0
Cookware                     945.0
Desktop Computers            879.0
Furniture                   5575.0
Gaming Consoles             2769.0
Home Decor                  5349.0
Kitchen Appliances          5255.0
Laptops                     2573.0
Small Kitchen Appliances    1763.0
Smart Home Devices          6153.0
Smartphones                 6153.0
TVs                         1890.0
Tablets                      865.0
Name: quantity, dtype: float64

In [45]:
transactions.groupby("product_category")["price"].mean()

product_category
Audio Equipment              282.297617
Bedding                      166.558404
Computer Accessories          85.617008
Cookware                     234.017642
Desktop Computers           1310.933109
Furniture                   1131.319625
Gaming Consoles              399.800865
Home Decor                   163.963989
Kitchen Appliances           568.576497
Laptops                     1543.525912
Small Kitchen Appliances     114.898002
Smart Home Devices           170.998102
Smartphones                  818.649018
TVs                         1722.793568
Tablets                      508.919076
Name: price, dtype: float64

In [46]:
transactions.groupby("payment_method").size()

payment_method
Apple Pay       3160
Cash            1573
Credit Card    10907
Debit Card      7968
Gift Card       1596
Google Pay      1633
PayPal          4798
dtype: int64

In [47]:
transactions.groupby("store_location").size()

store_location
Atlanta, GA           1563
Boston, MA            1528
Chicago, IL           1559
Denver, CO            1529
Houston, TX           1630
Los Angeles, CA       1470
Miami, FL             1587
New York, NY          1562
Online               16108
San Francisco, CA     1579
Seattle, WA           1536
dtype: int64

In [48]:
transactions.groupby("product_name")["quantity"].sum()

product_name
Air Fryer          351.0
Amazon Echo       1217.0
Amazon Fire HD     172.0
Area Rug          1139.0
Asus ROG           175.0
                   ...
Xbox Series X      545.0
Xiaomi Mi 12      1301.0
iMac               149.0
iPad Pro           158.0
iPhone 13         1257.0
Name: quantity, Length: 75, dtype: float64

In [49]:
transactions.groupby("store_location")["price"].mean()

store_location
Atlanta, GA          621.450025
Boston, MA           600.225786
Chicago, IL          638.619438
Denver, CO           636.789431
Houston, TX          652.167290
Los Angeles, CA      629.671041
Miami, FL            592.223265
New York, NY         640.478284
Online               621.117036
San Francisco, CA    619.150720
Seattle, WA          604.621162
Name: price, dtype: float64

In [50]:
transactions.groupby("product_category")["discount_applied"].sum()

product_category
Audio Equipment              9755.0
Bedding                      3080.0
Computer Accessories         3400.0
Cookware                     3070.0
Desktop Computers            3665.0
Furniture                   20390.0
Gaming Consoles              9675.0
Home Decor                  19430.0
Kitchen Appliances          19670.0
Laptops                     10035.0
Small Kitchen Appliances     6750.0
Smart Home Devices          21065.0
Smartphones                 22090.0
TVs                          7005.0
Tablets                      3760.0
Name: discount_applied, dtype: float64

In [51]:
transactions.groupby("store_location")["customer_id"].nunique()

store_location
Atlanta, GA          1073
Boston, MA           1045
Chicago, IL          1050
Denver, CO           1056
Houston, TX          1106
Los Angeles, CA      1017
Miami, FL            1085
New York, NY         1056
Online               2962
San Francisco, CA    1088
Seattle, WA          1041
Name: customer_id, dtype: int64

In [57]:
transactions["sales"]= transactions["price"] * transactions["quantity"]

In [136]:
transactions.groupby("product_category")["sales"].sum()

product_category
Audio Equipment             7.264193e+05
Bedding                     1.529210e+05
Computer Accessories        7.938287e+04
Cookware                    2.260882e+05
Desktop Computers           1.158941e+06
Furniture                   6.328533e+06
Gaming Consoles             1.143652e+06
Home Decor                  9.063421e+05
Kitchen Appliances          3.049974e+06
Laptops                     4.069916e+06
Small Kitchen Appliances    2.018979e+05
Smart Home Devices          1.054706e+06
Smartphones                 5.141941e+06
TVs                         3.362329e+06
Tablets                     4.526172e+05
Unknown                     6.021589e+05
Name: sales, dtype: float64

In [58]:
transactions.columns

Index(['transaction_id', 'customer_id', 'product_name', 'product_category',
       'quantity', 'price', 'transaction_date', 'store_location',
       'payment_method', 'discount_applied', 'sales'],
      dtype='str')

### 5.2 Merge

In [59]:
merged = pd.merge(customers,transactions , on="customer_id")

In [40]:
merged.head()

,customer_id,full_name,age,gender,email,phone,street_address,city,state,zip_code,...,preferred_channel,transaction_id,product_name,product_category,quantity,price,transaction_date,store_location,payment_method,discount_applied
0,4c30e132-0704-4459-a509-9eddde934977,Mark Johnson,40,Male,mark.johnson@yahoo.com,989.608.3863,819 Johnson Course,Houston,Texas,29158.0,...,NaN,ec438dca-2c1a-4769-ab19-e5310a92712a,Xiaomi Mi 12,Smartphones,1.0,955.37,2024-07-31,"Miami, FL",Credit Card,0.0
1,4c30e132-0704-4459-a509-9eddde934977,Mark Johnson,40,Male,mark.johnson@yahoo.com,989.608.3863,819 Johnson Course,Houston,Texas,29158.0,...,NaN,cd5c1596-bc06-479c-9556-e9abcdc1784c,Office Desk,Furniture,1.0,832.93,2024-08-23,"Denver, CO",Debit Card,NaN
2,4c30e132-0704-4459-a509-9eddde934977,Mark Johnson,40,Male,mark.johnson@yahoo.com,989.608.3863,819 Johnson Course,Houston,Texas,29158.0,...,NaN,2acd8488-0e95-405c-9639-de32d2b9291a,Dining Table,Furniture,1.0,1777.42,2024-12-17,"Chicago, IL",PayPal,0.0
3,68bec407-275f-4b5b-9a82-13d02f54626a,Robert Smith,33,Male,smithr@yahoo.com,(518)349-5931x0341,35116 Michael Key Suite 078,Austin,Texas,16862.0,...,in-store,035ce41a-e6b9-4b1c-abd8-a839f2539d4a,Electric Range,Kitchen Appliances,1.0,145.06,2023-12-02,"Denver, CO",Debit Card,0.0
4,68bec407-275f-4b5b-9a82-13d02f54626a,Robert Smith,33,Male,smithr@yahoo.com,(518)349-5931x0341,35116 Michael Key Suite 078,Austin,Texas,16862.0,...,in-store,21ad14b0-9310-4d8a-83cd-a53b04686a18,NaN,Kitchen Appliances,2.0,811.30,2022-11-11,"Los Angeles, CA",Apple Pay,0.0

In [61]:
merged.groupby("city")["sales"].sum()

city
Akron             312065.010000
Albany            554969.204485
Alexandria        217428.005296
Allentown         393651.819978
Ann Arbor         245962.915776
                      ...
Tucson            116960.800000
Vancouver         159214.291264
Virginia Beach    262861.212669
Winston-Salem     190831.352157
Worcester         193818.447428
Name: sales, Length: 74, dtype: float64

In [144]:
merged.groupby("gender").size()

gender
female               15514
male                 14885
non-binary             839
prefer not to say      327
unknown                730
dtype: int64

In [60]:
merged.groupby("preferred_channel")["sales"].sum()

preferred_channel
both        9.616093e+06
in-store    4.195728e+06
online      1.344225e+07
Name: sales, dtype: float64

In [75]:
merged.groupby("age")["sales"].mean()

age
18     923.022241
19     884.579255
20     900.102160
21    1079.961925
22    1009.882614
23     838.723936
24     926.111378
25     855.881081
26     794.381104
27    1195.667515
28     877.527353
29     885.095318
30     878.830985
31     807.078493
32     857.319020
33     776.123117
34     764.949040
35     858.882193
36     804.772615
37     874.868884
38     864.814113
39     807.714058
40     872.313726
41     806.655937
42     815.645209
43     860.938712
44     797.226111
45    1247.837653
46    1214.294008
47     957.616168
48     976.005690
49    1063.974037
50     845.516942
51    1054.013985
52    1105.281336
53     941.171764
54    1212.961050
55     903.603063
56    1212.103803
57     886.196102
58     914.713544
59    1255.179245
60    1047.218458
61     870.885843
62     822.239583
63     984.652158
64     746.466667
65    1650.896452
66    1340.747368
67     588.388571
68    1052.508182
69     410.003333
70     483.582308
71     886.575000
72     600.535000
73    1135.213333
80     236.121667
Name: sales, dtype: float64

In [147]:
merged.groupby("state")["quantity"].sum()

state
arizona           1454.0
california        8169.0
florida           5192.0
georgia           2113.0
illinois          2761.0
massachusetts     1321.0
michigan          2104.0
new jersey        1553.0
new york          4383.0
north carolina    2053.0
ohio              2489.0
pennsylvania      2846.0
texas             5779.0
virginia          1677.0
washington        1423.0
Name: quantity, dtype: float64

### 5.3 Pivot Table

In [151]:
merged.pivot_table(index="product_category" , columns="store_location" , values="quantity" , aggfunc="sum")

store_location,"Atlanta, GA","Boston, MA","Chicago, IL","Denver, CO","Houston, TX","Los Angeles, CA","Miami, FL","New York, NY",Online,"San Francisco, CA","Seattle, WA",Unknown
product_category,,,,,,,,,,,,
Audio Equipment,122.0,216.0,98.0,90.0,106.0,91.0,106.0,71.0,1452.0,98.0,76.0,59.0
Bedding,46.0,40.0,42.0,22.0,43.0,77.0,35.0,50.0,464.0,31.0,28.0,56.0
Computer Accessories,39.0,38.0,24.0,43.0,44.0,60.0,45.0,48.0,454.0,40.0,48.0,17.0
Cookware,37.0,47.0,36.0,34.0,45.0,45.0,41.0,38.0,526.0,54.0,38.0,14.0
Desktop Computers,52.0,30.0,42.0,52.0,37.0,43.0,39.0,39.0,440.0,50.0,44.0,20.0
Furniture,241.0,294.0,289.0,244.0,293.0,258.0,300.0,261.0,2752.0,301.0,288.0,124.0
Gaming Consoles,117.0,136.0,86.0,122.0,138.0,118.0,142.0,144.0,1529.0,89.0,111.0,61.0
Home Decor,231.0,290.0,278.0,280.0,230.0,287.0,274.0,269.0,2618.0,302.0,296.0,83.0
Kitchen Appliances,341.0,238.0,218.0,244.0,313.0,285.0,271.0,254.0,2542.0,306.0,233.0,93.0
Laptops,91.0,97.0,101.0,99.0,137.0,106.0,105.0,105.0,1524.0,106.0,89.0,49.0
Small Kitchen Appliances,83.0,66.0,90.0,93.0,104.0,76.0,69.0,67.0,883.0,99.0,134.0,25.0
Smart Home Devices,243.0,346.0,303.0,254.0,315.0,283.0,304.0,286.0,3219.0,286.0,300.0,100.0
Smartphones,291.0,292.0,330.0,267.0,336.0,366.0,260.0,290.0,3116.0,288.0,305.0,109.0
TVs,85.0,134.0,124.0,99.0,88.0,74.0,84.0,107.0,881.0,71.0,89.0,78.0
Tablets,52.0,38.0,52.0,43.0,31.0,23.0,49.0,33.0,462.0,41.0,51.0,9.0
Unknown,47.0,46.0,48.0,61.0,44.0,63.0,36.0,46.0,539.0,29.0,36.0,20.0

In [155]:
merged.pivot_table(index="product_category" , columns="payment_method" , values="sales" , aggfunc="sum")

payment_method,Apple Pay,Cash,Credit Card,Debit Card,Gift Card,Google Pay,PayPal,Unknown
product_category,,,,,,,,
Audio Equipment,71396.882404,37761.906353,2.574389e+05,1.772688e+05,32329.900000,38396.880000,95982.630000,15843.420000
Bedding,16335.702720,4848.910000,4.563312e+04,3.919442e+04,8813.720000,7953.340000,27202.249857,2939.490000
Computer Accessories,9382.900000,3025.180000,2.371646e+04,2.298285e+04,3431.160000,3775.830000,11138.195000,1930.290000
Cookware,26375.550000,12398.178184,7.241027e+04,5.779563e+04,10154.515000,11777.300000,32864.099971,2312.645000
Desktop Computers,112489.755000,49503.600000,3.638259e+05,3.404619e+05,61260.250000,59134.740000,155201.420000,17063.790000
Furniture,660058.244239,430194.184259,2.086081e+06,1.448542e+06,307488.255000,268305.300000,996079.375453,131784.466105
Gaming Consoles,98127.400091,44822.790000,4.114974e+05,2.869731e+05,47653.950000,40892.587665,178393.982802,35290.940000
Home Decor,86598.883034,52216.405557,3.324739e+05,1.980045e+05,53989.635236,44363.588357,126452.603533,12242.540000
Kitchen Appliances,280093.939318,139270.985000,1.066181e+06,8.110043e+05,146291.657498,128770.390000,424587.436104,53774.120000
Laptops,384529.800000,184809.224891,1.561500e+06,1.003992e+06,138790.815000,206290.760000,516450.345000,73553.560000
Small Kitchen Appliances,23891.170000,7497.370000,7.200243e+04,5.052178e+04,7269.840000,9329.815000,27193.195000,4192.250000
Smart Home Devices,96128.135076,43124.769133,3.579317e+05,2.743020e+05,44354.235000,47341.735000,172227.637155,19295.546923
Smartphones,526590.278835,248617.990000,1.716907e+06,1.213697e+06,237104.798657,223656.074449,872209.117458,103160.070000
TVs,324627.827904,159032.255501,1.049558e+06,1.045091e+06,146261.940000,150832.250000,440911.524208,46013.660000
Tablets,39133.866957,21317.070000,1.607002e+05,1.147574e+05,23864.825000,15285.380000,71768.555000,5789.930000
Unknown,47926.785000,21670.920000,2.044828e+05,1.157983e+05,22158.910000,35429.460000,148332.404406,6359.300000

In [157]:
merged.pivot_table(index="product_category" , columns="store_location"  , aggfunc="size")

store_location,"Atlanta, GA","Boston, MA","Chicago, IL","Denver, CO","Houston, TX","Los Angeles, CA","Miami, FL","New York, NY",Online,"San Francisco, CA","Seattle, WA",Unknown
product_category,,,,,,,,,,,,
Audio Equipment,94,99,82,72,67,76,85,57,1068,77,61,46
Bedding,35,30,32,18,35,31,28,34,336,25,22,13
Computer Accessories,31,32,22,34,34,27,37,39,292,30,34,16
Cookware,29,36,28,25,29,33,29,25,320,46,27,12
Desktop Computers,39,24,32,41,32,28,31,31,324,34,32,16
Furniture,188,204,213,192,233,171,205,199,1813,196,198,93
Gaming Consoles,66,72,67,79,90,68,82,82,1085,67,89,45
Home Decor,181,208,196,200,189,171,209,194,1692,203,192,69
Kitchen Appliances,207,177,170,185,200,186,192,193,1732,205,172,74
Laptops,71,78,79,78,99,82,73,86,1056,81,69,37
Small Kitchen Appliances,66,51,70,68,76,63,53,55,659,71,78,21
Smart Home Devices,189,202,197,197,205,196,226,220,2167,220,218,77
Smartphones,226,181,217,202,219,232,203,208,2209,220,207,83
TVs,64,71,79,74,65,61,64,80,644,55,69,20
Tablets,44,28,37,38,25,19,39,27,342,27,41,7
Unknown,33,35,38,26,32,26,31,32,369,22,27,15

In [158]:
merged.pivot_table(index="product_category" , columns="city"  , values="sales", aggfunc="sum")

city,akron,albany,alexandria,allentown,ann arbor,arlington,athens,atlanta,augusta,austin,...,tallahassee,tampa,tempe,toledo,trenton,tucson,vancouver,virginia beach,winston-salem,worcester
product_category,,,,,,,,,,,,,,,,,,,,,
Audio Equipment,3761.91,14602.110000,2663.980000,11171.640000,5107.110000,2155.670000,5837.960000,5678.650000,4876.51,18080.860000,...,14720.900000,13124.888356,1596.20,4096.570000,15997.891393,3080.02,4908.320000,3708.551532,3544.860000,3890.400000
Bedding,1903.58,3299.650000,525.440000,1778.640000,964.590000,1615.630000,1053.020000,1415.860000,1044.87,3051.190000,...,2640.710000,9798.130000,366.48,2167.910000,533.170000,1159.12,384.900000,979.940000,432.180000,830.330000
Computer Accessories,557.35,1241.575000,281.800000,1427.990000,354.560000,462.110000,195.970000,701.430000,283.70,1428.930000,...,2215.594230,1089.330000,280.84,784.490000,1234.324940,622.55,405.330000,263.710000,156.040000,180.090000
Cookware,1747.74,2539.890000,756.420000,3165.440000,1799.420000,539.500000,2157.190000,2293.830000,1609.72,5488.685000,...,6983.480000,4382.430000,574.00,1771.000000,1339.540000,823.01,1048.720000,1803.060000,401.250000,4842.408579
Desktop Computers,8550.89,25816.130000,10189.320000,16674.800000,17930.510000,7763.430000,7439.340000,10333.070000,4261.10,72702.710000,...,27705.070000,23953.550000,3411.38,6917.510000,8060.030000,1068.84,7591.380000,14398.180000,5545.170000,9899.080000
Furniture,113344.74,139023.578533,36509.655000,100246.490000,69190.360000,66825.825000,50995.790000,34522.290000,46921.45,181458.010000,...,122788.507157,106175.340000,15571.58,70655.590000,36041.800000,29184.49,48626.930000,81755.541138,27870.180000,38264.155000
Gaming Consoles,23584.42,26343.440000,8827.760000,9291.110000,3511.000000,27855.560000,7611.917802,10755.440000,7561.63,23228.550000,...,41958.820000,14784.870000,5008.76,4637.320000,7113.540000,7522.04,13855.920000,9399.850000,8999.810000,8696.460000
Home Decor,7391.94,16736.980000,4935.900000,10401.394387,8575.330000,9499.709044,16697.930000,6808.040000,5585.12,24101.090000,...,29487.461055,18254.080000,2463.94,6413.350000,6750.245955,5411.90,2810.630000,11283.750000,9233.450000,6769.340000
Kitchen Appliances,23333.05,60461.780000,38726.879154,60108.660506,29901.685000,8712.070000,27251.430000,19199.190000,21337.00,80458.321374,...,60172.580000,57500.966862,29273.18,33403.431129,23715.960000,13211.26,20800.590000,28811.110000,13443.910000,26661.198849
Laptops,33630.14,84229.730000,32490.410000,62799.220000,14808.860000,14412.110000,40470.530000,36946.070000,34437.89,142636.150000,...,80053.740000,108865.685000,11572.12,32696.970000,24586.260000,7905.11,5494.470000,22369.590000,40970.510000,27103.130000
Small Kitchen Appliances,3114.90,3566.190000,2993.460000,2154.635000,3160.155776,1357.940000,1233.510000,2083.480000,3246.80,3807.240000,...,3449.410000,3658.320000,1674.77,3079.190000,1419.670000,1184.18,1358.610000,2070.190000,1711.845000,1963.740000
Smart Home Devices,10397.82,17394.195953,7740.806143,11459.960000,11472.560000,8350.339329,7814.980000,11789.350433,5056.16,23712.480000,...,29254.880000,19062.645000,5548.82,9050.800000,6248.620000,5045.49,9176.051264,7351.270000,6375.630000,8194.780000
Smartphones,42586.13,124117.140000,58669.220000,58613.650085,36644.250000,25358.820000,36373.440000,27160.270000,78741.44,108824.050000,...,113820.760000,68338.650000,14064.23,44934.380000,39873.644850,24190.12,32455.510000,41711.900000,43433.342157,46636.700000
TVs,27000.94,30625.180000,13636.820000,41688.510000,43485.560000,16889.470000,13991.790000,20778.340000,25723.50,115947.775501,...,48533.790000,75245.690000,22116.85,27872.280000,9521.090000,16889.58,8698.940000,33138.350000,31688.570000,11788.650000
Tablets,4648.06,7469.930000,505.160000,5888.040000,2037.450000,301.370000,4275.515000,4506.710000,6241.54,10452.560000,...,8714.480000,17415.841315,1684.10,4797.480000,1348.080000,1595.58,3870.710000,4044.770000,2660.240000,2557.870000
Unknown,14340.61,8859.530000,925.250000,8053.750000,2473.090000,437.840000,2997.130000,5540.760000,5146.69,18770.080000,...,10240.360000,8473.370000,357.27,11348.670000,5513.230000,2508.42,2545.360000,7163.060000,248.000000,1098.190000

In [160]:
merged.pivot_table(index="gender" , columns="preferred_channel" , values="customer_id"  , aggfunc="nunique")

preferred_channel  both  in-store  online
gender
female              681       386    1112
male                594       439    1041
non-binary           35        22      57
prefer not to say    19         8      23
unknown              33        16      49